### ISSUE TITLE
一直报错= =

### ISSUE THREAD

**Issue by Aruelius** [codingEcho/blog#2]
ok了

**Comment by MikuShare** [comment]
这个已经解决了，就是在后台运行监听转换这里。
![qq 20171113163628](https://user-images.githubusercontent.com/25380989/32716461-17df313a-c891-11e7-8f23-c6e963eb5a08.png)，检测到ftp上传的临时文件。

**Comment by MikuShare** [comment]
并且通过网页上传的图片好像都不会被检测到。
